# Generated by Django 5.0.2 on 2024-02-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("localidades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cidade",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cidades",
                to="localidades.estado",
            ),
        ),
        migrations.AlterField(
            model_name="estado",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estados",
                to="localidades.pais",
            ),
        ),
    ]
