# Generated by Django 4.2 on 2024-02-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0002_alter_cidade_estado_alter_estado_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AddField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
