# Generated by Django 5.0.2 on 2024-02-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("localidades", "0002_alter_cidade_estado_alter_estado_pais"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Estadual", "Estadual"),
                            ("Nacional", "Nacional"),
                            ("Internacional", "Internacional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[("COPA", "copa"), ("CAMPEONATO", "campeonato")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("ano_fundacao", models.IntegerField()),
                ("divisao_atual", models.CharField(max_length=1)),
                (
                    "escudo",
                    models.ImageField(
                        height_field=50, max_length=50, upload_to=None, width_field=50
                    ),
                ),
                ("titulos", models.IntegerField()),
                (
                    "modalidade",
                    models.CharField(
                        choices=[("F", "Feminino"), ("M", "Masculino")], max_length=10
                    ),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="times",
                        to="localidades.cidade",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="times",
                        to="localidades.pais",
                    ),
                ),
                (
                    "uf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="times",
                        to="localidades.estado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("foto", models.ImageField(upload_to="")),
                ("posicao", models.CharField(max_length=20)),
                ("numero_camisa", models.IntegerField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("F", "Feminino"), ("M", "Masculino")], max_length=10
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Time",
                        to="Times.time",
                    ),
                ),
            ],
        ),
    ]
