# Generated by Django 5.0.2 on 2024-02-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Times", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="divisao_atual",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="time",
            name="escudo",
            field=models.ImageField(upload_to="escudos"),
        ),
    ]
