# Generated by Django 5.0.2 on 2024-02-21 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Times", "0002_alter_time_divisao_atual_alter_time_escudo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="escudo",
            field=models.ImageField(upload_to="Times/escudos"),
        ),
        migrations.CreateModel(
            name="Titulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("ano_conquista", models.IntegerField()),
                ("colocacao", models.CharField(max_length=10)),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Times",
                        to="Times.time",
                    ),
                ),
            ],
        ),
    ]
