# Generated by Django 4.2 on 2024-02-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Times', '0007_competicao_time_alter_titulo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='categoria',
            field=models.CharField(choices=[('COPA', 'COPA'), ('CAMPEONATO', 'CAMPEONATO')], max_length=10),
        ),
    ]
